### PR TITLE
Login

### PR DESCRIPTION
**Pull request by DatThanhPham**

### CODE REVIEW

**Review by dnduc789 — COMMENTED** [review]
Do vertical not horizontal

**Comment by DatThanhPham** [comment]
> Do vertical not horizontal

I've fixed it. please check

**Comment by dnduc789** [comment]
1. username input use placeholder instead
2. position of password input should equal with username input

**Comment by dnduc789** [comment]
Submit button should have space below 20px

**Review by dnduc789 — APPROVED** [review]

**Pull request merged**
